# this_file: Cargo.toml
[workspace]
members = ["crates/uubed-core", "crates/uubed-tm", "crates/uubed-python"]
default-members = ["crates/uubed-core", "crates/uubed-tm"]
resolver = "2"

[workspace.package]
version = "1.0.12"
edition = "2021"
rust-version = "1.88"
authors = ["Adam Twardoch <adam+github@twardoch.com>"]
license = "MIT"
repository = "https://github.com/twardoch/uubed-rs"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
strip = true

# Profile for development with some optimizations
[profile.dev-opt]
inherits = "dev"
opt-level = 2         # Some optimization for bearable performance